import pandas as pd


vehicles_path = '../../data/roberto/system_optimum/vehicles.csv'
df = pd.read_csv(vehicles_path)
# print("@@@@@@@@@@@@@@@@ value @@@@@@@@@@@@@@@@")
# print("mean")
# print(df.groupby(['veh_id']).mean())
# print("sum")
# print(df.groupby(['veh_id']).sum())
# print("mean mean")
# print(df.groupby(['veh_id']).mean().mean()['time'])
# print("mean sum")
# print(df.groupby(['veh_id']).mean().sum()['time'])
# print("sum mean")
# print(df.groupby(['veh_id']).sum().mean()['time'])
# print("sum sum")
# print(df.groupby(['veh_id']).sum().sum()['time'])
# print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
# print("$$$$$$$$$$$$$$$$ value $$$$$$$$$$$$$$$$")
# print("mean")
# print(df.groupby(['run']).mean())
# print("sum")
# print(df.groupby(['run']).sum())
# print("mean mean")
# print(df.groupby(['run']).mean().mean()['time'])
# print("mean sum")
# print(df.groupby(['run']).mean().sum()['time'])
# print("sum mean")
# print(df.groupby(['run']).sum().mean()['time'])
# print("sum sum")
# print(df.groupby(['run']).sum().sum()['time'])
# print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("################ value ################")
# print("mean")
# print(df.groupby(['veh_id','run']).mean())
# print("sum")
# print(df.groupby(['veh_id','run']).sum())
# print("mean mean")
# print(df.groupby(['veh_id','run']).mean().mean()['time'])
# print("mean sum")
# print(df.groupby(['veh_id','run']).mean().sum()['time'])
print("sum mean")
print(df.groupby(['veh_id','run']).sum().mean()['time'])
# print("sum sum")
# print(df.groupby(['veh_id','run']).sum().sum()['time'])
print("#######################################")
# print("**************** value ****************")
# print("mean")
# print(df.groupby(['run', 'veh_id']).mean())
# print("sum")
# print(df.groupby(['run', 'veh_id']).sum())
# print("mean mean")
# print(df.groupby(['run', 'veh_id']).mean().mean()['time'])
# print("mean sum")
# print(df.groupby(['run', 'veh_id']).mean().sum()['time'])
# print("sum mean")
# print(df.groupby(['run', 'veh_id']).sum().mean()['time'])
# print("sum sum")
# print(df.groupby(['run', 'veh_id']).sum().sum()['time'])
# print("***************************************")